toolchain: Add Espressif ESP32 and ESP32S2 support
zephyrproject-rtos/sdk-ng pull request #426
Opened 2022-02-17 20:47 UTC by sylvioalves

2022-02-18 02:00 UTC, sylvioalves commented
@galak, not sure if the buildkite error is indeed an error. Would you check?

2022-02-18 02:19 UTC, sylvioalves commented
@stephanosio @galak We analyzed all the patches in Espressif's gcc/gdb/newlib repository and concluded that we can have it as is (without patches). We will submit some patches upstream eventually, but there is no blocking patch at all to have it integrated in Zephyr.  
However, this won't work in Zephyr with latest branch, of course. I will submit a PR with a bunch of changes to enable the usage of this new toolchain. Can you suggest me a way to synchronize this?

2022-02-18 07:57 UTC, stephanosio commented
> However, this won't work in Zephyr with latest branch, of course.

Do you mean the "ESP32 toolchain" built using the changes in this PR is not able to build working binaries for the ESP32 SoC? If so, this PR should be considered a draft until it can.

> Can you suggest me a way to synchronize this?

If you have ESP32-specific patches for the binutils, gcc and newlib, please create a pull request in the relevant Zephyr fork repositories and update this PR to reference them (you can set `*_DEVEL_REVISION` to `pull/(PR NUMBER)/head`).

2022-02-18 11:23 UTC, sylvioalves commented
@stephanosio Yes, current main branch can't be build using the toolchain from this PR. I am working out a PR to enabled this (I have it all working locally already).
Regarding patches, I won't submit any patch at all as it works as is.

2022-03-08 18:13 UTC, stephanosio requested changes
Please specify the source (URL) and version of the `xtensa_espressif_esp32.tar.gz` and `xtensa_espressif_esp32s2.tar.gz` added here in the commit message.

2022-03-08 18:13 UTC, stephanosio commented
Also noting that this needs to be tested against https://github.com/zephyrproject-rtos/zephyr/pull/43534/.

2022-03-08 19:32 UTC, sylvioalves commented
> Please specify the source (URL) and version of the `xtensa_espressif_esp32.tar.gz` and `xtensa_espressif_esp32s2.tar.gz` added here in the commit message.

I added the github URL in the commit message. The .tar.gz file was manually created.

2022-03-09 06:16 UTC, stephanosio commented
> I added the github URL in the commit message.

@sylvioalves Thanks. Please add the version/tag or commit (in `xtensa-overlay` repository) from which the tarball was created in the commit message as well. This will make identifying the current version of overlays we have in the sdk-ng repository much easier, in case we ever need to update these overlays in the future.

2022-03-09 06:19 UTC, stephanosio reviewed
Looks ok overall.

DNM until the build failures described in https://github.com/zephyrproject-rtos/zephyr/pull/43534#pullrequestreview-903701217 are resolved, in case they require Zephyr SDK-side changes.

2022-03-11 11:22 UTC, stephanosio commented
Postponing this to 0.14.1, which will be a quick follow-up to 0.14.0 (multi-platform SDK) in a month or so.

2022-03-20 05:15 UTC, stephanosio requested changes
There has been a slight change to the way the toolchain components are referenced in the configs (#444).

Could you update the PR as follows?

2022-03-20 05:15 UTC, stephanosio commented on configs/xtensa-espressif_esp32_zephyr-elf.config
> +CT_BINUTILS_DEVEL_REVISION="c7d30a54fc17c1e9d9b1c39c7623222442c63af8"
```suggestion
CT_BINUTILS_SRC_CUSTOM=y
CT_BINUTILS_CUSTOM_LOCATION="${GITHUB_WORKSPACE}/binutils"
```

2022-03-20 05:15 UTC, stephanosio commented on configs/xtensa-espressif_esp32_zephyr-elf.config
> +CT_NEWLIB_DEVEL_REVISION="2893dbb10f1fe3bf431a26f89a22e12a5020dc02"
```suggestion
CT_NEWLIB_SRC_CUSTOM=y
CT_NEWLIB_CUSTOM_LOCATION="${GITHUB_WORKSPACE}/newlib"
```

2022-03-20 05:15 UTC, stephanosio commented on configs/xtensa-espressif_esp32_zephyr-elf.config
> +CT_GCC_DEVEL_REVISION="8c1f3dcc6eddf3392d77f56c9bed69e5d6446cdf"
```suggestion
CT_GCC_SRC_CUSTOM=y
CT_GCC_CUSTOM_LOCATION="${GITHUB_WORKSPACE}/gcc"
```

2022-03-20 05:15 UTC, stephanosio commented on configs/xtensa-espressif_esp32_zephyr-elf.config
> +CT_GDB_DEVEL_REVISION="76b05e962501d75d995b9f9dd13f837df36b7208"
```suggestion
CT_GDB_SRC_CUSTOM=y
CT_GDB_CUSTOM_LOCATION="${GITHUB_WORKSPACE}/gdb"
```

2022-03-20 05:15 UTC, stephanosio commented on configs/xtensa-espressif_esp32_zephyr-elf.config
> +CT_NEWLIB_NANO_DEVEL_REVISION="2893dbb10f1fe3bf431a26f89a22e12a5020dc02"
```suggestion
CT_NEWLIB_NANO_SRC_CUSTOM=y
CT_NEWLIB_NANO_CUSTOM_LOCATION="${GITHUB_WORKSPACE}/newlib"
```

2022-03-20 05:15 UTC, stephanosio commented on configs/xtensa-espressif_esp32s2_zephyr-elf.config
> +CT_BINUTILS_DEVEL_REVISION="c7d30a54fc17c1e9d9b1c39c7623222442c63af8"
```suggestion
CT_BINUTILS_SRC_CUSTOM=y
CT_BINUTILS_CUSTOM_LOCATION="${GITHUB_WORKSPACE}/binutils"
```

2022-03-20 05:15 UTC, stephanosio commented on configs/xtensa-espressif_esp32s2_zephyr-elf.config
> +CT_NEWLIB_DEVEL_REVISION="2893dbb10f1fe3bf431a26f89a22e12a5020dc02"
```suggestion
CT_NEWLIB_SRC_CUSTOM=y
CT_NEWLIB_CUSTOM_LOCATION="${GITHUB_WORKSPACE}/newlib"
```

2022-03-20 05:15 UTC, stephanosio commented on configs/xtensa-espressif_esp32s2_zephyr-elf.config
> +CT_GCC_DEVEL_REVISION="8c1f3dcc6eddf3392d77f56c9bed69e5d6446cdf"
```suggestion
CT_GCC_SRC_CUSTOM=y
CT_GCC_CUSTOM_LOCATION="${GITHUB_WORKSPACE}/gcc"
```

2022-03-20 05:15 UTC, stephanosio commented on configs/xtensa-espressif_esp32s2_zephyr-elf.config
> +CT_GDB_DEVEL_REVISION="76b05e962501d75d995b9f9dd13f837df36b7208"
```suggestion
CT_GDB_SRC_CUSTOM=y
CT_GDB_CUSTOM_LOCATION="${GITHUB_WORKSPACE}/gdb"
```

2022-03-20 05:15 UTC, stephanosio commented on configs/xtensa-espressif_esp32s2_zephyr-elf.config
> +CT_NEWLIB_NANO_DEVEL_REVISION="2893dbb10f1fe3bf431a26f89a22e12a5020dc02"
```suggestion
CT_NEWLIB_NANO_SRC_CUSTOM=y
CT_NEWLIB_NANO_CUSTOM_LOCATION="${GITHUB_WORKSPACE}/newlib"
```

2022-03-21 11:23 UTC, stephanosio requested changes
Thanks for the update. It looks like the GDB source configs were duplicated in the `xtensa-espressif_esp32_zephyr-elf.config` (specified GDB instead of Binutils at the top).

Also I found a few extra changes to be made; it would be good to address them while we are at it.

2022-03-21 11:23 UTC, stephanosio commented on configs/xtensa-espressif_esp32_zephyr-elf.config
> +CT_GDB_CUSTOM_LOCATION="${GITHUB_WORKSPACE}/gdb"
You have specified GDB source configs twice, this needs to be:
```
CT_BINUTILS_SRC_CUSTOM=y
CT_BINUTILS_CUSTOM_LOCATION="${GITHUB_WORKSPACE}/binutils"
```

2022-03-21 11:23 UTC, stephanosio commented on configs/xtensa-espressif_esp32_zephyr-elf.config
> +CT_GDB_CROSS_BUILD_NO_PYTHON=y
Please remove this too as per https://github.com/zephyrproject-rtos/sdk-ng/commit/5abd8f7db6f53d7ba994a93d82d7fde783a3c691.

2022-03-21 11:23 UTC, stephanosio commented on configs/xtensa-espressif_esp32s2_zephyr-elf.config
> +CT_GDB_CROSS_BUILD_NO_PYTHON=y
Please remove this too as per https://github.com/zephyrproject-rtos/sdk-ng/commit/5abd8f7db6f53d7ba994a93d82d7fde783a3c691.

2022-03-21 11:23 UTC, stephanosio commented on configs/xtensa-espressif_esp32_zephyr-elf.config
> +CT_LOCAL_TARBALLS_DIR="${CT_PREFIX:-${HOME}/x-tools}/sources"
Please remove this as per https://github.com/zephyrproject-rtos/sdk-ng/commit/006aef1658fd51999d482dd28642e9d834adde3a.

2022-03-21 11:23 UTC, stephanosio commented on configs/xtensa-espressif_esp32s2_zephyr-elf.config
> +CT_LOCAL_TARBALLS_DIR="${CT_PREFIX:-${HOME}/x-tools}/sources"
Please remove this as per https://github.com/zephyrproject-rtos/sdk-ng/commit/006aef1658fd51999d482dd28642e9d834adde3a.

2022-03-21 11:32 UTC, sylvioalves commented
> Thanks for the update. It looks like the GDB source configs were duplicated in the `xtensa-espressif_esp32_zephyr-elf.config` (specified GDB instead of Binutils at the top).
> 
> Also I found a few extra changes to be made; it would be good to address them while we are at it.

Thanks for pointing that out.

2022-03-21 14:38 UTC, stephanosio approved these changes
Looks ok overall.

Pending tests.

2022-03-21 17:38 UTC, stephanosio commented
Ran full twister build on the `esp32` and `esp32s2_saola` boards with https://github.com/zephyrproject-rtos/zephyr/pull/43534/commits/6e952a06d0a435ffdfb777a1eb99915f4207dca3 (#43534), verified that all test builds succeed (build only, no hardware runs).

2022-03-21 17:39 UTC, merged