xtensa: add rt500_adsp toolchain
zephyrproject-rtos/sdk-ng pull request #696
Opened 2023-08-18 14:20 UTC by dbaluta

This adds the Xtensa toolchain for Tensilica Fusion F1 DSP found on NXP RT500 MCU family.

2023-08-18 20:01 UTC, dcpleung requested changes
Also, please remove `linux/` and `u-boot/` as we do not need those.

2023-08-21 07:15 UTC, dbaluta commented
@dcpleung thanks for review. Fixed.

2023-08-21 16:15 UTC, dcpleung approved these changes

2023-08-22 18:34 UTC, mmahadevan108 approved these changes

2023-08-25 20:40 UTC, merged