support c11 and c++11 threads, mutexes, condition variables, etc
zephyrproject-rtos/sdk-ng pull request #735
Opened 2024-02-11 12:42 UTC by cfriedt

Enable C11 and C++11 threads in gcc and g++.

2024-02-14 03:43 UTC, dkalowsk approved these changes
Neat!

2024-02-17 11:21 UTC, cfriedt commented
There is one additional change that I would like to integrate here, and that's namely to use thed_sleep() instead of nanosleep() in gthread scenarios.

Once that is done-ish, I will publish all of the PRs needed and probably bring it to the arch meeting to give a bit of an overview and request some additional testers.

A trivial implementation of C11 threads can probably also be added to newlib (and picolibc). Likely the same one that exists in Zephyr today. 

These are all changes that should be  upstreamed, which is nice because it will take some of the implementation out of Zephyr.

At the same time, we should be able to override that part of the libc and later provide a POSIX-less implementation of C11 threads that is more optimized for Zephyr.

By extension, at that point, we will also then have POSIX-less C++11 thread support.

2024-02-19 11:20 UTC, cfriedt commented
* added support for `thrd_sleep()` (which is ISO C11) instead of `nanosleep()` (which is POSIX) in gcc/libstdc++-v3

2024-03-02 11:37 UTC, cfriedt commented
This can probably be opened for review at this point. Likely I should make PRs for submodules too.

2024-03-06 22:58 UTC, cfriedt commented
Two additional patches needed
Defines to get the required visibility and library behaviour.
```diff
diff --git a/libgcc/gthr-c11.h b/libgcc/gthr-c11.h
index 3cadb110d96..db2cc7a46f7 100644
--- a/libgcc/gthr-c11.h
+++ b/libgcc/gthr-c11.h
@@ -45,6 +45,10 @@ see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
 #define _GTHREAD_USE_COND_INIT_FUNC 1
 #define __GTHREAD_COND_INIT_FUNCTION __gthread_cond_init_function
 
+#define _GLIBCXX_THREAD_ABI_COMPAT 1
+#define _GLIBCXX_HAS_GTHREADS 1
+#define _GLIBCXX_USE_THRD_SLEEP 1
+
 #include <threads.h>
 #include <time.h>
 
```

Include the header for `shared_ptr`, which is used in one area.
```diff
diff --git a/libstdc++-v3/include/bits/std_thread.h b/libstdc++-v3/include/bits/std_thread.h
index dd625de3bc3..413ad4c9e09 100644
--- a/libstdc++-v3/include/bits/std_thread.h
+++ b/libstdc++-v3/include/bits/std_thread.h
@@ -41,6 +41,7 @@
 #include <bits/invoke.h>       // std::__invoke
 #include <bits/refwrap.h>       // not required, but helpful to users
 #include <bits/unique_ptr.h>   // std::unique_ptr
+#include <bits/shared_ptr.h>   // std::shared_ptr
 
 #ifdef _GLIBCXX_HAS_GTHREADS
 # include <bits/gthr.h>
 ```

2024-03-08 18:03 UTC, dkalowsk approved these changes
haven't been able to review the submodule changes but the configs changes look good

2024-03-08 19:12 UTC, cfriedt commented
> haven't been able to review the submodule changes but the configs changes look good

@dkalowsk - I still need to make an `aarch64-zephyr-elf` toolchain for you. Oddly, it does not pick up the correct bits from `common.config`. `x86_64-zephyr-elf` required additional config bits too.

2024-03-09 18:21 UTC, cfriedt commented
<img width="734" alt="Screenshot 2024-03-09 at 1 19 55 PM" src="https://github.com/zephyrproject-rtos/sdk-ng/assets/983494/2870ed53-91f3-4136-a4bb-b4e2055576b2">
<img width="628" alt="Screenshot 2024-03-09 at 1 20 31 PM" src="https://github.com/zephyrproject-rtos/sdk-ng/assets/983494/533de7a4-4d6e-415d-a409-a7a4d004e293">
<img width="672" alt="Screenshot 2024-03-09 at 1 20 55 PM" src="https://github.com/zephyrproject-rtos/sdk-ng/assets/983494/8a8edba9-163a-4bfb-9b0d-8a3af1317ccf">
<img width="529" alt="Screenshot 2024-03-09 at 1 21 23 PM" src="https://github.com/zephyrproject-rtos/sdk-ng/assets/983494/7f50146e-5843-4ab3-8535-668f9e3cfe9b">

2024-03-10 13:12 UTC, cfriedt commented
cc @xenulswatching

2024-03-27 12:26 UTC, stephanosio requested changes
LGTM

DNM until the submodule refs are updated.

2024-03-28 12:17 UTC, nordicjm approved these changes

2024-04-03 03:03 UTC, stephanosio commented
@cfriedt Could you please rebase and update the submodule modules to point to the merged commits?

2024-04-03 06:29 UTC, cfriedt commented
@stephanosio - should be updated now.

2024-04-04 04:46 UTC, stephanosio approved these changes

2024-04-04 04:47 UTC, merged