xtensa: sample_controller32: for Xtensa MPU support
zephyrproject-rtos/sdk-ng pull request #748
Opened 2024-04-24 18:10 UTC by dcpleung

The overlay comes from:

  https://github.com/jcmvbkbc/xtensa-toolchain-build
    commit 435c5e8b108de520565886f3f2349cc6be3fe712
    under directory overlays/

This would allow us to use QEMU to test the Xtensa MPU code on main Zephyr repo.

2024-05-06 09:42 UTC, stephanosio reviewed
Need to update `ci.yml` to build the new `xtensa-sample_controller32_zephyr-elf` toolchain.

Also QEMU changes from https://github.com/zephyrproject-rtos/qemu/pull/8 should be pulled as well.

2024-05-13 20:20 UTC, dcpleung commented
I have changed `ci.yml` and the QEMU SHA. Hopefully I have modified in the correct place.

2024-05-28 16:50 UTC, dcpleung commented
This needs https://github.com/zephyrproject-rtos/qemu/pull/9 to fix QEMU build.

2024-08-15 03:00 UTC, stephanosio commented
@dcpleung https://github.com/zephyrproject-rtos/qemu/pull/9 is merged. Please update this PR to point to the merged commit.

2024-08-15 15:39 UTC, dcpleung commented
> @dcpleung [zephyrproject-rtos/qemu#9](https://github.com/zephyrproject-rtos/qemu/pull/9) is merged. Please update this PR to point to the merged commit.

Done. Updated the QEMU `SRCREV`.

2024-09-27 00:32 UTC, stephanosio commented
Test run: https://github.com/zephyrproject-rtos/sdk-ng/actions/runs/11062364153/job/30736729508

2024-09-27 11:32 UTC, stephanosio requested changes

2024-09-27 11:32 UTC, stephanosio commented on .github/workflows/ci.yml
> +              ;;
This needs to be disabled until the board support is merged on the Zephyr side; otherwise, CI will fail.

2024-09-27 11:54 UTC, stephanosio commented on .github/workflows/ci.yml
> +              ;;
Done

2024-09-27 11:54 UTC, stephanosio approved these changes

2024-09-27 11:54 UTC, merged