scripts: Fix using deprecated/removed wget option
zephyrproject-rtos/sdk-ng pull request #836
Opened 2024-11-20 22:46 UTC by jhedberg

Recent wget versions don't have the --show-progress option anymore and will generate a "wget: unrecognized option '--show-progress'" error (this happens e.g. with latest Fedora). The correct option to use seems to be --progress=bar, which should do the same thing.

2024-11-20 22:46 UTC, jhedberg commented
Note: I wasn't able to verify this on Windows, but I'd assume the same option should work there as well.

2024-11-21 01:20 UTC, stephanosio requested changes
**`wget2` is not `wget`**, and Fedora made a mistake of trying to replace `wget` with `wget2`.

See https://github.com/zephyrproject-rtos/sdk-ng/issues/771#issuecomment-2359913981.

Fedora should fix this, not us.

2024-11-21 01:20 UTC, stephanosio commented on scripts/template_setup_posix
> +  wget -q --progress=bar -N -O "${toolchain_filename}" "${toolchain_uri}"
This results in progress bar not showing up at all in the "real wget."

2024-11-21 08:33 UTC, jhedberg commented
Thanks @stephanosio, I wasn't aware of this wget vs wget2 distinction. I completely agree Fedora is at fault, however the current end result is that new Zephyr users who follow our getting started guide end up having a negative experience - I wonder if there's something we could still do, e.g. mention this somewhere in the documentation, or even try to work around it in the setup script?

2024-11-21 08:33 UTC, closed without merging